version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    env_file:
      - .env
    depends_on:
      - database
    entrypoint: 
      - /bin/sh
      - -c
      - |
        set -e
        export PATH="$PATH:/root/.dotnet/tools"
        dotnet ef database update --project /src/RadensuasoTodo.Api/RadensuasoTodo.Api.csproj --startup-project /src/RadensuasoTodo.Api/RadensuasoTodo.Api.csproj
        dotnet /app/RadensuasoTodo.Api.dll

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
