version: "3.8"

services:
  web:
    build:
      context: .
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_KEY=${JWT_KEY}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - FRONTEND_URL=${FRONTEND_URL}
    depends_on:
      - database
    entrypoint:
      - /bin/sh
      - -c
      - |
        set -e
        dotnet ef database update --no-build --project /src/RadensuasoTodo.Api/RadensuasoTodo.Api.csproj --startup-project /src/RadensuasoTodo.Api/RadensuasoTodo.Api.csproj
        dotnet /app/RadensuasoTodo.Api.dll

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
